"""empty message

Revision ID: eb6e6ce32db0
Revises: 
Create Date: 2024-02-28 09:00:25.386052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6e6ce32db0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('lawfirms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lawfirmName', sa.String(length=255), nullable=False),
    sa.Column('businessAddress', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('practiceArea', sa.String(length=255), nullable=False),
    sa.Column('barAssociationsMembership', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('logoImage', sa.String(length=111100000000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lawfirms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lawfirms_id'), ['id'], unique=False)

    op.create_table('lawyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('linkedIn', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('education', sa.String(length=1000), nullable=False),
    sa.Column('barLicenseNumber', sa.String(length=255), nullable=False),
    sa.Column('practiceArea', sa.String(length=250), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('price', sa.String(length=10), nullable=False),
    sa.Column('image', sa.String(length=1111000000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lawyers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lawyers_id'), ['id'], unique=False)

    op.create_table('book_appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullName', sa.String(length=255), nullable=False),
    sa.Column('phoneNumber', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('appointmentDate', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('communicationPreferences', sa.String(length=255), nullable=False),
    sa.Column('appointmentTime', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lawyer_id', sa.Integer(), nullable=True),
    sa.Column('lawfirm_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lawfirm_id'], ['lawfirms.id'], ),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_appointments')
    with op.batch_alter_table('lawyers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lawyers_id'))

    op.drop_table('lawyers')
    with op.batch_alter_table('lawfirms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lawfirms_id'))

    op.drop_table('lawfirms')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
